USE [master]
GO
/****** Object:  Database [Warehouse-App] ******/
CREATE DATABASE [Warehouse-App]
GO
ALTER DATABASE [Warehouse-App] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Warehouse-App].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Warehouse-App] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Warehouse-App] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Warehouse-App] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Warehouse-App] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Warehouse-App] SET ARITHABORT OFF 
GO
ALTER DATABASE [Warehouse-App] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Warehouse-App] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Warehouse-App] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Warehouse-App] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Warehouse-App] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Warehouse-App] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Warehouse-App] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Warehouse-App] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Warehouse-App] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Warehouse-App] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Warehouse-App] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Warehouse-App] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Warehouse-App] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Warehouse-App] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Warehouse-App] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Warehouse-App] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Warehouse-App] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Warehouse-App] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Warehouse-App] SET  MULTI_USER 
GO
ALTER DATABASE [Warehouse-App] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Warehouse-App] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Warehouse-App] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Warehouse-App] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Warehouse-App] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Warehouse-App] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Warehouse-App] SET QUERY_STORE = OFF
GO
USE [Warehouse-App]
GO
/****** Object:  Table [dbo].[Customers] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[NIP] [varchar](50) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NULL,
	[ProductId] [int] NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Quantity] [int] NULL,
	[Price] [int] NULL,
	[Category] [varchar](50) NULL,
	[Details] [varchar](50) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Warehouse-App] SET  READ_WRITE 
GO
